/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RisalahRouteImport } from './routes/risalah'
import { Route as RefleksiRouteImport } from './routes/refleksi'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistorySessionIdRouteImport } from './routes/history.$sessionId'

const RisalahRoute = RisalahRouteImport.update({
  id: '/risalah',
  path: '/risalah',
  getParentRoute: () => rootRouteImport,
} as any)
const RefleksiRoute = RefleksiRouteImport.update({
  id: '/refleksi',
  path: '/refleksi',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySessionIdRoute = HistorySessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/pricing': typeof PricingRoute
  '/refleksi': typeof RefleksiRoute
  '/risalah': typeof RisalahRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/pricing': typeof PricingRoute
  '/refleksi': typeof RefleksiRoute
  '/risalah': typeof RisalahRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/pricing': typeof PricingRoute
  '/refleksi': typeof RefleksiRoute
  '/risalah': typeof RisalahRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/pricing'
    | '/refleksi'
    | '/risalah'
    | '/history/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/pricing'
    | '/refleksi'
    | '/risalah'
    | '/history/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/pricing'
    | '/refleksi'
    | '/risalah'
    | '/history/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  PricingRoute: typeof PricingRoute
  RefleksiRoute: typeof RefleksiRoute
  RisalahRoute: typeof RisalahRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/risalah': {
      id: '/risalah'
      path: '/risalah'
      fullPath: '/risalah'
      preLoaderRoute: typeof RisalahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refleksi': {
      id: '/refleksi'
      path: '/refleksi'
      fullPath: '/refleksi'
      preLoaderRoute: typeof RefleksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$sessionId': {
      id: '/history/$sessionId'
      path: '/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof HistorySessionIdRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface HistoryRouteChildren {
  HistorySessionIdRoute: typeof HistorySessionIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistorySessionIdRoute: HistorySessionIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRouteWithChildren,
  PricingRoute: PricingRoute,
  RefleksiRoute: RefleksiRoute,
  RisalahRoute: RisalahRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
