// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artwork struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	ImageUrl    string             `json:"image_url"`
	UnlockCost  int32              `json:"unlock_cost"`
	RevealCost  int32              `json:"reveal_cost"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          string             `json:"user_id"`
	Status          string             `json:"status"`
	TotalMessages   int32              `json:"total_messages"`
	GoldenInkEarned int32              `json:"golden_ink_earned"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserArtwork struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	ArtworkID   pgtype.UUID        `json:"artwork_id"`
	Progress    int32              `json:"progress"`
	Status      string             `json:"status"`
	UnlockedAt  pgtype.Timestamptz `json:"unlocked_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserStat struct {
	UserID         string             `json:"user_id"`
	GoldenInk      int32              `json:"golden_ink"`
	Marble         int32              `json:"marble"`
	CurrentStreak  int32              `json:"current_streak"`
	LongestStreak  int32              `json:"longest_streak"`
	LastActiveDate pgtype.Date        `json:"last_active_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Level          int32              `json:"level"`
	CurrentXp      int32              `json:"current_xp"`
	TotalXp        int32              `json:"total_xp"`
}

type WeeklySummary struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       string             `json:"user_id"`
	WeekStart    pgtype.Date        `json:"week_start"`
	WeekEnd      pgtype.Date        `json:"week_end"`
	Summary      string             `json:"summary"`
	SessionCount int32              `json:"session_count"`
	MessageCount int32              `json:"message_count"`
	Emotions     []byte             `json:"emotions"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
