// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGoldenInk = `-- name: AddGoldenInk :one
UPDATE user_stats
SET golden_ink = golden_ink + $2, updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, golden_ink, marble, current_streak, longest_streak, last_active_date, created_at, updated_at
`

type AddGoldenInkParams struct {
	UserID    string `json:"user_id"`
	GoldenInk int32  `json:"golden_ink"`
}

func (q *Queries) AddGoldenInk(ctx context.Context, arg AddGoldenInkParams) (UserStat, error) {
	row := q.db.QueryRow(ctx, addGoldenInk, arg.UserID, arg.GoldenInk)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.GoldenInk,
		&i.Marble,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addMarble = `-- name: AddMarble :one
UPDATE user_stats
SET marble = marble + $2, updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, golden_ink, marble, current_streak, longest_streak, last_active_date, created_at, updated_at
`

type AddMarbleParams struct {
	UserID string `json:"user_id"`
	Marble int32  `json:"marble"`
}

func (q *Queries) AddMarble(ctx context.Context, arg AddMarbleParams) (UserStat, error) {
	row := q.db.QueryRow(ctx, addMarble, arg.UserID, arg.Marble)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.GoldenInk,
		&i.Marble,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addSessionGoldenInk = `-- name: AddSessionGoldenInk :one
UPDATE sessions
SET 
    golden_ink_earned = golden_ink_earned + $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, total_messages, golden_ink_earned, started_at, ended_at, created_at, updated_at
`

type AddSessionGoldenInkParams struct {
	ID              pgtype.UUID `json:"id"`
	GoldenInkEarned int32       `json:"golden_ink_earned"`
}

func (q *Queries) AddSessionGoldenInk(ctx context.Context, arg AddSessionGoldenInkParams) (Session, error) {
	row := q.db.QueryRow(ctx, addSessionGoldenInk, arg.ID, arg.GoldenInkEarned)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalMessages,
		&i.GoldenInkEarned,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countMessagesBySession = `-- name: CountMessagesBySession :one
SELECT COUNT(*) FROM messages
WHERE session_id = $1
`

func (q *Queries) CountMessagesBySession(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMessagesBySession = `-- name: CountUserMessagesBySession :one
SELECT COUNT(*) FROM messages
WHERE session_id = $1 AND role = 'user'
`

func (q *Queries) CountUserMessagesBySession(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMessagesBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtwork = `-- name: CreateArtwork :one
INSERT INTO artworks (name, display_name, description, image_url, unlock_cost, reveal_cost)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, display_name, description, image_url, unlock_cost, reveal_cost, created_at
`

type CreateArtworkParams struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
	ImageUrl    string `json:"image_url"`
	UnlockCost  int32  `json:"unlock_cost"`
	RevealCost  int32  `json:"reveal_cost"`
}

func (q *Queries) CreateArtwork(ctx context.Context, arg CreateArtworkParams) (Artwork, error) {
	row := q.db.QueryRow(ctx, createArtwork,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.ImageUrl,
		arg.UnlockCost,
		arg.RevealCost,
	)
	var i Artwork
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ImageUrl,
		&i.UnlockCost,
		&i.RevealCost,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one

INSERT INTO messages (session_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, session_id, role, content, created_at
`

type CreateMessageParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Role      string      `json:"role"`
	Content   string      `json:"content"`
}

// ==================== MESSAGES ====================
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.SessionID, arg.Role, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id)
VALUES ($1)
RETURNING id, user_id, status, total_messages, golden_ink_earned, started_at, ended_at, created_at, updated_at
`

// ==================== SESSIONS ====================
func (q *Queries) CreateSession(ctx context.Context, userID string) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalMessages,
		&i.GoldenInkEarned,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserStats = `-- name: CreateUserStats :one
INSERT INTO user_stats (user_id)
VALUES ($1)
RETURNING user_id, golden_ink, marble, current_streak, longest_streak, last_active_date, created_at, updated_at
`

func (q *Queries) CreateUserStats(ctx context.Context, userID string) (UserStat, error) {
	row := q.db.QueryRow(ctx, createUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.GoldenInk,
		&i.Marble,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWeeklySummary = `-- name: CreateWeeklySummary :one

INSERT INTO weekly_summaries (user_id, week_start, week_end, summary, session_count, message_count, emotions)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, week_start, week_end, summary, session_count, message_count, emotions, created_at
`

type CreateWeeklySummaryParams struct {
	UserID       string      `json:"user_id"`
	WeekStart    pgtype.Date `json:"week_start"`
	WeekEnd      pgtype.Date `json:"week_end"`
	Summary      string      `json:"summary"`
	SessionCount int32       `json:"session_count"`
	MessageCount int32       `json:"message_count"`
	Emotions     []byte      `json:"emotions"`
}

// ==================== WEEKLY SUMMARIES ====================
func (q *Queries) CreateWeeklySummary(ctx context.Context, arg CreateWeeklySummaryParams) (WeeklySummary, error) {
	row := q.db.QueryRow(ctx, createWeeklySummary,
		arg.UserID,
		arg.WeekStart,
		arg.WeekEnd,
		arg.Summary,
		arg.SessionCount,
		arg.MessageCount,
		arg.Emotions,
	)
	var i WeeklySummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.WeekEnd,
		&i.Summary,
		&i.SessionCount,
		&i.MessageCount,
		&i.Emotions,
		&i.CreatedAt,
	)
	return i, err
}

const endSession = `-- name: EndSession :one
UPDATE sessions
SET 
    status = $2,
    ended_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, status, total_messages, golden_ink_earned, started_at, ended_at, created_at, updated_at
`

type EndSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
	UserID string      `json:"user_id"`
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, endSession, arg.ID, arg.Status, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalMessages,
		&i.GoldenInkEarned,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, status, total_messages, golden_ink_earned, started_at, ended_at, created_at, updated_at FROM sessions
WHERE user_id = $1 AND status = 'active'
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSession(ctx context.Context, userID string) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSession, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalMessages,
		&i.GoldenInkEarned,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtworkByID = `-- name: GetArtworkByID :one
SELECT id, name, display_name, description, image_url, unlock_cost, reveal_cost, created_at FROM artworks
WHERE id = $1
`

func (q *Queries) GetArtworkByID(ctx context.Context, id pgtype.UUID) (Artwork, error) {
	row := q.db.QueryRow(ctx, getArtworkByID, id)
	var i Artwork
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ImageUrl,
		&i.UnlockCost,
		&i.RevealCost,
		&i.CreatedAt,
	)
	return i, err
}

const getArtworkByName = `-- name: GetArtworkByName :one
SELECT id, name, display_name, description, image_url, unlock_cost, reveal_cost, created_at FROM artworks
WHERE name = $1
`

func (q *Queries) GetArtworkByName(ctx context.Context, name string) (Artwork, error) {
	row := q.db.QueryRow(ctx, getArtworkByName, name)
	var i Artwork
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ImageUrl,
		&i.UnlockCost,
		&i.RevealCost,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentArtwork = `-- name: GetCurrentArtwork :one
SELECT 
    ua.id, ua.user_id, ua.artwork_id, ua.progress, ua.status, ua.unlocked_at, ua.completed_at, ua.created_at, ua.updated_at,
    a.name,
    a.display_name,
    a.description,
    a.image_url,
    a.unlock_cost,
    a.reveal_cost
FROM user_artworks ua
JOIN artworks a ON ua.artwork_id = a.id
WHERE ua.user_id = $1 AND ua.status = 'in_progress'
ORDER BY ua.unlocked_at DESC
LIMIT 1
`

type GetCurrentArtworkRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	ArtworkID   pgtype.UUID        `json:"artwork_id"`
	Progress    int32              `json:"progress"`
	Status      string             `json:"status"`
	UnlockedAt  pgtype.Timestamptz `json:"unlocked_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	ImageUrl    string             `json:"image_url"`
	UnlockCost  int32              `json:"unlock_cost"`
	RevealCost  int32              `json:"reveal_cost"`
}

func (q *Queries) GetCurrentArtwork(ctx context.Context, userID string) (GetCurrentArtworkRow, error) {
	row := q.db.QueryRow(ctx, getCurrentArtwork, userID)
	var i GetCurrentArtworkRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArtworkID,
		&i.Progress,
		&i.Status,
		&i.UnlockedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ImageUrl,
		&i.UnlockCost,
		&i.RevealCost,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, status, total_messages, golden_ink_earned, started_at, ended_at, created_at, updated_at FROM sessions
WHERE id = $1 AND user_id = $2
`

type GetSessionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalMessages,
		&i.GoldenInkEarned,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserArtwork = `-- name: GetUserArtwork :one

SELECT id, user_id, artwork_id, progress, status, unlocked_at, completed_at, created_at, updated_at FROM user_artworks
WHERE user_id = $1 AND artwork_id = $2
`

type GetUserArtworkParams struct {
	UserID    string      `json:"user_id"`
	ArtworkID pgtype.UUID `json:"artwork_id"`
}

// ==================== USER ARTWORKS ====================
func (q *Queries) GetUserArtwork(ctx context.Context, arg GetUserArtworkParams) (UserArtwork, error) {
	row := q.db.QueryRow(ctx, getUserArtwork, arg.UserID, arg.ArtworkID)
	var i UserArtwork
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArtworkID,
		&i.Progress,
		&i.Status,
		&i.UnlockedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one

SELECT user_id, golden_ink, marble, current_streak, longest_streak, last_active_date, created_at, updated_at FROM user_stats WHERE user_id = $1
`

// ==================== USER STATS ====================
func (q *Queries) GetUserStats(ctx context.Context, userID string) (UserStat, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.GoldenInk,
		&i.Marble,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeeklySummary = `-- name: GetWeeklySummary :one
SELECT id, user_id, week_start, week_end, summary, session_count, message_count, emotions, created_at FROM weekly_summaries
WHERE user_id = $1 AND week_start = $2
`

type GetWeeklySummaryParams struct {
	UserID    string      `json:"user_id"`
	WeekStart pgtype.Date `json:"week_start"`
}

func (q *Queries) GetWeeklySummary(ctx context.Context, arg GetWeeklySummaryParams) (WeeklySummary, error) {
	row := q.db.QueryRow(ctx, getWeeklySummary, arg.UserID, arg.WeekStart)
	var i WeeklySummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.WeekEnd,
		&i.Summary,
		&i.SessionCount,
		&i.MessageCount,
		&i.Emotions,
		&i.CreatedAt,
	)
	return i, err
}

const incrementSessionMessages = `-- name: IncrementSessionMessages :one
UPDATE sessions
SET 
    total_messages = total_messages + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, total_messages, golden_ink_earned, started_at, ended_at, created_at, updated_at
`

func (q *Queries) IncrementSessionMessages(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, incrementSessionMessages, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalMessages,
		&i.GoldenInkEarned,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtworks = `-- name: ListArtworks :many

SELECT id, name, display_name, description, image_url, unlock_cost, reveal_cost, created_at FROM artworks
ORDER BY unlock_cost ASC
`

// ==================== ARTWORKS ====================
func (q *Queries) ListArtworks(ctx context.Context) ([]Artwork, error) {
	rows, err := q.db.Query(ctx, listArtworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artwork{}
	for rows.Next() {
		var i Artwork
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.ImageUrl,
			&i.UnlockCost,
			&i.RevealCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, content, created_at FROM messages
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, status, total_messages, golden_ink_earned, started_at, ended_at, created_at, updated_at FROM sessions
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListSessionsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalMessages,
			&i.GoldenInkEarned,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserArtworks = `-- name: ListUserArtworks :many
SELECT 
    ua.id, ua.user_id, ua.artwork_id, ua.progress, ua.status, ua.unlocked_at, ua.completed_at, ua.created_at, ua.updated_at,
    a.name,
    a.display_name,
    a.description,
    a.image_url,
    a.unlock_cost,
    a.reveal_cost
FROM user_artworks ua
JOIN artworks a ON ua.artwork_id = a.id
WHERE ua.user_id = $1
ORDER BY ua.created_at DESC
`

type ListUserArtworksRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	ArtworkID   pgtype.UUID        `json:"artwork_id"`
	Progress    int32              `json:"progress"`
	Status      string             `json:"status"`
	UnlockedAt  pgtype.Timestamptz `json:"unlocked_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	ImageUrl    string             `json:"image_url"`
	UnlockCost  int32              `json:"unlock_cost"`
	RevealCost  int32              `json:"reveal_cost"`
}

func (q *Queries) ListUserArtworks(ctx context.Context, userID string) ([]ListUserArtworksRow, error) {
	rows, err := q.db.Query(ctx, listUserArtworks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserArtworksRow{}
	for rows.Next() {
		var i ListUserArtworksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ArtworkID,
			&i.Progress,
			&i.Status,
			&i.UnlockedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.ImageUrl,
			&i.UnlockCost,
			&i.RevealCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeklySummaries = `-- name: ListWeeklySummaries :many
SELECT id, user_id, week_start, week_end, summary, session_count, message_count, emotions, created_at FROM weekly_summaries
WHERE user_id = $1
ORDER BY week_start DESC
LIMIT $2 OFFSET $3
`

type ListWeeklySummariesParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListWeeklySummaries(ctx context.Context, arg ListWeeklySummariesParams) ([]WeeklySummary, error) {
	rows, err := q.db.Query(ctx, listWeeklySummaries, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeeklySummary{}
	for rows.Next() {
		var i WeeklySummary
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeekStart,
			&i.WeekEnd,
			&i.Summary,
			&i.SessionCount,
			&i.MessageCount,
			&i.Emotions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendGoldenInk = `-- name: SpendGoldenInk :one
UPDATE user_stats
SET golden_ink = golden_ink - $2, updated_at = NOW()
WHERE user_id = $1 AND golden_ink >= $2
RETURNING user_id, golden_ink, marble, current_streak, longest_streak, last_active_date, created_at, updated_at
`

type SpendGoldenInkParams struct {
	UserID    string `json:"user_id"`
	GoldenInk int32  `json:"golden_ink"`
}

func (q *Queries) SpendGoldenInk(ctx context.Context, arg SpendGoldenInkParams) (UserStat, error) {
	row := q.db.QueryRow(ctx, spendGoldenInk, arg.UserID, arg.GoldenInk)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.GoldenInk,
		&i.Marble,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const spendMarble = `-- name: SpendMarble :one
UPDATE user_stats
SET marble = marble - $2, updated_at = NOW()
WHERE user_id = $1 AND marble >= $2
RETURNING user_id, golden_ink, marble, current_streak, longest_streak, last_active_date, created_at, updated_at
`

type SpendMarbleParams struct {
	UserID string `json:"user_id"`
	Marble int32  `json:"marble"`
}

func (q *Queries) SpendMarble(ctx context.Context, arg SpendMarbleParams) (UserStat, error) {
	row := q.db.QueryRow(ctx, spendMarble, arg.UserID, arg.Marble)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.GoldenInk,
		&i.Marble,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlockArtwork = `-- name: UnlockArtwork :one
INSERT INTO user_artworks (user_id, artwork_id, status, unlocked_at)
VALUES ($1, $2, 'in_progress', NOW())
RETURNING id, user_id, artwork_id, progress, status, unlocked_at, completed_at, created_at, updated_at
`

type UnlockArtworkParams struct {
	UserID    string      `json:"user_id"`
	ArtworkID pgtype.UUID `json:"artwork_id"`
}

func (q *Queries) UnlockArtwork(ctx context.Context, arg UnlockArtworkParams) (UserArtwork, error) {
	row := q.db.QueryRow(ctx, unlockArtwork, arg.UserID, arg.ArtworkID)
	var i UserArtwork
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArtworkID,
		&i.Progress,
		&i.Status,
		&i.UnlockedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtworkProgress = `-- name: UpdateArtworkProgress :one
UPDATE user_artworks
SET 
    progress = $3,
    status = CASE WHEN $3 >= 100 THEN 'completed' ELSE status END,
    completed_at = CASE WHEN $3 >= 100 THEN NOW() ELSE completed_at END,
    updated_at = NOW()
WHERE user_id = $1 AND artwork_id = $2
RETURNING id, user_id, artwork_id, progress, status, unlocked_at, completed_at, created_at, updated_at
`

type UpdateArtworkProgressParams struct {
	UserID    string      `json:"user_id"`
	ArtworkID pgtype.UUID `json:"artwork_id"`
	Progress  int32       `json:"progress"`
}

func (q *Queries) UpdateArtworkProgress(ctx context.Context, arg UpdateArtworkProgressParams) (UserArtwork, error) {
	row := q.db.QueryRow(ctx, updateArtworkProgress, arg.UserID, arg.ArtworkID, arg.Progress)
	var i UserArtwork
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArtworkID,
		&i.Progress,
		&i.Status,
		&i.UnlockedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStreak = `-- name: UpdateStreak :one
UPDATE user_stats
SET 
    current_streak = $2,
    longest_streak = GREATEST(longest_streak, $2),
    last_active_date = $3,
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, golden_ink, marble, current_streak, longest_streak, last_active_date, created_at, updated_at
`

type UpdateStreakParams struct {
	UserID         string      `json:"user_id"`
	CurrentStreak  int32       `json:"current_streak"`
	LastActiveDate pgtype.Date `json:"last_active_date"`
}

func (q *Queries) UpdateStreak(ctx context.Context, arg UpdateStreakParams) (UserStat, error) {
	row := q.db.QueryRow(ctx, updateStreak, arg.UserID, arg.CurrentStreak, arg.LastActiveDate)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.GoldenInk,
		&i.Marble,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserStats = `-- name: UpsertUserStats :one
INSERT INTO user_stats (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET updated_at = NOW()
RETURNING user_id, golden_ink, marble, current_streak, longest_streak, last_active_date, created_at, updated_at
`

func (q *Queries) UpsertUserStats(ctx context.Context, userID string) (UserStat, error) {
	row := q.db.QueryRow(ctx, upsertUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.GoldenInk,
		&i.Marble,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
